// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA68g7y_QxmC8bvRVTI-rRNNUSEbrEuCRY',
    appId: '1:623151828674:web:5fe4c614fc8839db4e355b',
    messagingSenderId: '623151828674',
    projectId: 'attendora-a0fc5',
    authDomain: 'attendora-a0fc5.firebaseapp.com',
    storageBucket: 'attendora-a0fc5.firebasestorage.app',
    measurementId: 'G-81XLWREGSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB241-eOHGI0OOukCp3XOyWphNS-kXsVd4',
    appId: '1:623151828674:android:b4c9784d56022fb24e355b',
    messagingSenderId: '623151828674',
    projectId: 'attendora-a0fc5',
    storageBucket: 'attendora-a0fc5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA68g7y_QxmC8bvRVTI-rRNNUSEbrEuCRY',
    appId: '1:623151828674:web:ca90f25b5be8e89f4e355b',
    messagingSenderId: '623151828674',
    projectId: 'attendora-a0fc5',
    authDomain: 'attendora-a0fc5.firebaseapp.com',
    storageBucket: 'attendora-a0fc5.firebasestorage.app',
    measurementId: 'G-60WW562SEP',
  );
}
