import 'dart:convert';
import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:flutter/foundation.dart';

class DeviceService {
  static final DeviceInfoPlugin _deviceInfo = DeviceInfoPlugin();

  /// Returns a unique, algorithmic identifier for the device.
  /// This ID is generated by hashing multiple stable device parameters.
  /// It is designed to be:
  /// 1. Unique per device
  /// 2. Persistent (same ID even after clearing app data)
  /// 3. Strict (changes if core hardware/browser environment changes)
  static Future<String?> getDeviceId() async {
    try {
      String rawFingerprint;

      if (kIsWeb) {
        final webInfo = await _deviceInfo.webBrowserInfo;
        final window = PlatformDispatcher.instance.views.first;

        // Web Fingerprint Components
        final components = [
          'vendor: ${webInfo.vendor}',
          'userAgent: ${webInfo.userAgent}', // Note: Browser updates will change this ID (Strict)
          'hardwareConcurrency: ${webInfo.hardwareConcurrency}',
          'deviceMemory: ${webInfo.deviceMemory}',
          'language: ${webInfo.language}',
          'platform: ${webInfo.platform}',
          'product: ${webInfo.product}',
          'maxTouchPoints: ${webInfo.maxTouchPoints}',
          'timezone: ${DateTime.now().timeZoneName}',
          'screen: ${window.physicalSize.width}x${window.physicalSize.height}@${window.devicePixelRatio}',
        ];

        rawFingerprint = components.join('|');
      } else if (Platform.isAndroid) {
        final androidInfo = await _deviceInfo.androidInfo;

        // Android Fingerprint Components
        // androidId is the strongest anchor, but we combine others for "algorithmic" robustness
        final components = [
          'androidId: ${androidInfo.id}',
          'brand: ${androidInfo.brand}',
          'device: ${androidInfo.device}',
          'model: ${androidInfo.model}',
          'manufacturer: ${androidInfo.manufacturer}',
          'product: ${androidInfo.product}',
          'hardware: ${androidInfo.hardware}',
          'isPhysicalDevice: ${androidInfo.isPhysicalDevice}',
        ];

        rawFingerprint = components.join('|');
      } else if (Platform.isIOS) {
        final iosInfo = await _deviceInfo.iosInfo;

        final components = [
          'identifierForVendor: ${iosInfo.identifierForVendor}',
          'name: ${iosInfo.name}',
          'systemName: ${iosInfo.systemName}',
          'model: ${iosInfo.model}',
          'localizedModel: ${iosInfo.localizedModel}',
          'isPhysicalDevice: ${iosInfo.isPhysicalDevice}',
        ];

        rawFingerprint = components.join('|');
      } else {
        // Fallback for other platforms
        return null;
      }

      // Generate SHA-256 Hash
      final bytes = utf8.encode(rawFingerprint);
      final digest = sha256.convert(bytes);

      return digest.toString();
    } catch (e) {
      debugPrint('Error getting device ID: $e');
      return null;
    }
  }
}
